### ISSUE TITLE
Code Annotation Submissions

### ISSUE THREAD

**Issue by tashiad** [isabellevillasenor/crate#25]
Each person in group follow instructions [here](https://mod4.turing.io/projects/crate/code_annotation_submission.html)

Each person will want to create their own branch for the code annotations. The code annotations should be made in the files where you expect to be adding additional code. The annotations should be comments about what code already exists in the file.

You'll want to add the comments in the existing file, but yes it should remain on a branch and not be merged into main.

- [x] Alice
- [x] Catherine
- [x] Gabrielle
- [x] Isabelle
- [x] Rachel
- [x] Tashia

**Comment by gaj23** [comment]
Should we link our branches? Would that be helpful/is it unneeded.
